[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# this fixes conflicts between the 2 versions of openzeppelin
auto_detect_remappings = false

# remappings are in remappings.txt

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
